### ISSUE TITLE
Conditional body ID missing (only) on production

### ISSUE THREAD

**Issue by ndarville** [hafniatimes/issues#22]
Development: `<body id=“frontpage”>`
Production: `<body>`

And that’s using a fresh git clone.

![hafniatimes.com](https://cloud.githubusercontent.com/assets/198682/18680671/07559488-7f65-11e6-8d5d-053e8a948460.png)

![localhost](https://cloud.githubusercontent.com/assets/198682/18680673/09dbfb2a-7f65-11e6-86d9-840a7b033e11.png)

No idea why it’s handled differently.

**Comment by ndarville** [comment]
Could be due to a different Jekyll version?

**Comment by ndarville** [comment]
Updating `github-pages` from v78 to v96 reproduced the problem.

v79 is the update that breaks the layout.

**Comment by ndarville** [comment]
To be submitted as issue:

### Reproduction

``` sh
git clone github.com:hafniatimes/hafniatimes.github.io repo
cd repo
bundle install
# jekyll serve
```

``` sh
# Change jekyll-pages version from 78 to 79
bundle install
# jekyll serve
```

The broken part of the front page:

``` liquid
<body{% if page.section == "frontpage" %} id="frontpage"{% endif %}>
```

### Diff

``` sh
$ diff index.v78.html index.v79.html 
```

``` diff
25,26d24
<         <link rel="shorturl" href="http://hafnia.co/" />
< 
81,89d78
<             <link
<                 rel="alternate"
<                 hreflang="da"
<                 href="/da/"
<             />
<             <meta property="og:locale:alternate" content="da" />
< 
< 
< 
106a96,97
>         <meta property="og:type" content="article" />
> 
118c109
<     <body id="frontpage">
---
>     <body>
```

**Comment by DirtyF** [comment]
Here is a quickfix for default.html

`<body{% if layout.section == "frontpage" %} id="frontpage"{% endif %}>`
